function(_recipe_SDL2_toolchain)
  if(EMSCRIPTEN)
    add_library(SDL2 INTERFACE)
    target_compile_options(SDL2 INTERFACE "-sUSE_SDL=2")
    target_link_options(SDL2 INTERFACE "-sUSE_SDL=2")
  endif()
endfunction()

function(_recipe_SDL2_system)
  if(CL_STATIC)
    find_package(PkgConfig QUIET)
    if(PkgConfig_FOUND)
      pkg_check_modules(SDL2 IMPORTED_TARGET GLOBAL "--static" "sdl2>=2.0.0")
    endif()
  else()
    if(NOT CMAKE_CROSSCOMPILING)
      find_package(SDL2 QUIET)
    endif()

    if(NOT TARGET SDL2 AND NOT TARGET SDL2::SDL2)
      find_package(PkgConfig QUIET)
      if(PkgConfig_FOUND)
        pkg_check_modules(SDL2 IMPORTED_TARGET GLOBAL "sdl2>=2.0.0")
      endif()
    endif()
  endif()
endfunction()

function(_recipe_SDL2_package)
  if(CL_REQUIRE_STATIC)
    # Skip package manager stage if static is strictly required (system package managers rarely provide static SDL2)
    return()
  endif()

  if(CATALOG_PACKAGE_MANAGER STREQUAL "apt" OR CL_PACKAGE_MANAGER STREQUAL "apt")
    set(CL_PACKAGE_NAME "libsdl2-dev" PARENT_SCOPE)
  elseif(CATALOG_PACKAGE_MANAGER STREQUAL "pacman" OR CL_PACKAGE_MANAGER STREQUAL "pacman")
    set(CL_PACKAGE_NAME "sdl2" PARENT_SCOPE)
  elseif(CATALOG_PACKAGE_MANAGER STREQUAL "brew" OR CL_PACKAGE_MANAGER STREQUAL "brew")
    set(CL_PACKAGE_NAME "sdl2" PARENT_SCOPE)
  elseif(CATALOG_PACKAGE_MANAGER STREQUAL "yum" OR CL_PACKAGE_MANAGER STREQUAL "yum")
    set(CL_PACKAGE_NAME "SDL2-devel" PARENT_SCOPE)
  elseif(CATALOG_PACKAGE_MANAGER STREQUAL "apk" OR CL_PACKAGE_MANAGER STREQUAL "apk")
    set(CL_PACKAGE_NAME "sdl2-dev" PARENT_SCOPE)
  elseif(CATALOG_PACKAGE_MANAGER STREQUAL "zypper" OR CL_PACKAGE_MANAGER STREQUAL "zypper")
    set(CL_PACKAGE_NAME "libSDL2-devel" PARENT_SCOPE)
  endif()
endfunction()

function(_recipe_SDL2_source)
  set(SDL_BUILD_SHARED "ON")
  set(SDL_BUILD_STATIC "ON")

  if(CL_REQ_TYPE STREQUAL "STATIC" OR CL_REQ_TYPE STREQUAL "PREFER_STATIC")
    set(SDL_BUILD_SHARED "OFF")
    set(SDL_BUILD_STATIC "ON")
  elseif(CL_REQ_TYPE STREQUAL "SHARED" OR CL_REQ_TYPE STREQUAL "PREFER_SHARED")
    set(SDL_BUILD_SHARED "ON")
    set(SDL_BUILD_STATIC "OFF")
  endif()

  cl_import_source(
    NAME SDL2
    URL https://github.com/libsdl-org/SDL/archive/refs/tags/release-2.32.10.tar.gz
    OPTIONS "SDL_SHARED" "${SDL_BUILD_SHARED}" "SDL_STATIC" "${SDL_BUILD_STATIC}" "SDL_TEST" "OFF"
  )
endfunction()
