#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENTRY_FILE="${SCRIPT_DIR}/cmake/catalog.cmake"

MINIFY=false
OUTPUT_FILE=""

# flags
while [[ $# -gt 0 ]]; do
  case "$1" in
    --no-minify|-n)
      MINIFY=false
      shift
      ;;
    --minify|-m)
      MINIFY=true
      shift
      ;;
    -h|--help)
      echo "Usage: $0 [--minify|-m] [OUTPUT_FILE]"
      exit 0
      ;;
    -*)
      echo "Error: Unknown option $1" >&2
      exit 1
      ;;
    *)
      if [[ -z "${OUTPUT_FILE}" ]]; then
        OUTPUT_FILE="$1"
      else
        echo "Error: Unexpected argument $1" >&2
        exit 1
      fi
      shift
      ;;
  esac
done

OUTPUT_FILE="${OUTPUT_FILE:-"${SCRIPT_DIR}/catalog.cmake"}"
mkdir -p "$(dirname "${OUTPUT_FILE}")"

bundle_raw() {
  while IFS= read -r line || [[ -n "$line" ]]; do
    if [[ "$line" =~ include\(\$\{CMAKE_CURRENT_LIST_DIR\}/internal/(.+)\) ]]; then
      local rel_path="${BASH_REMATCH[1]}"
      local target_file="${SCRIPT_DIR}/cmake/internal/${rel_path}"

      if [[ -f "${target_file}" ]]; then
        if [[ "${MINIFY}" == "false" ]]; then
          echo "# --- Begin: internal/${rel_path} ---"
        fi
        cat "${target_file}"
        echo ""
        if [[ "${MINIFY}" == "false" ]]; then
          echo "# --- End: internal/${rel_path} ---"
          echo ""
        fi
      else
        echo "Error: Internal dependency missing at ${target_file}" >&2
        exit 1
      fi
    else
      echo "${line}"
    fi
  done < "${ENTRY_FILE}"
}

cat << 'EOF' > "${OUTPUT_FILE}"
# ==============================================================================
# AUTOMATICALLY GENERATED FILE - DO NOT EDIT DIRECTLY
# Generated by Catalog's bundle script
# ==============================================================================
EOF

if [[ "${MINIFY}" == "true" ]]; then
  bundle_raw | sed -E \
    -e 's/^[[:space:]]*#.*$//' \
    -e 's/^(([^"]*"[^"]*")*[^"]*)[[:space:]]*#.*$/\1/' \
    -e 's/^[[:space:]]+//' \
    -e 's/[[:space:]]+$//' \
    -e 's/[[:space:]]+/ /g' \
    -e '/^$/d' >> "${OUTPUT_FILE}"
  echo "Successfully bundled and minified Catalog into ${OUTPUT_FILE}"
else
  bundle_raw >> "${OUTPUT_FILE}"
  echo "Successfully bundled Catalog (unminified) into ${OUTPUT_FILE}"
fi
