include(${CMAKE_CURRENT_LIST_DIR}/internal/utils.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/internal/recipe.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/internal/resolve.cmake)

function(_catalog_impl_repo)
  if(ARGC EQUAL 0)
    set(REPO_SOURCE "catalog-cmake/repo")
  else()
    set(REPO_SOURCE "${ARGV0}")
  endif()
  _catalog_load_repo_meta(${REPO_SOURCE})
endfunction()

function(_catalog_impl_add_recipe PACKAGE_NAME RECIPE_SOURCE)
  _catalog_valid_target_name("${PACKAGE_NAME}" VALID_PKG)
  if(NOT VALID_PKG)
    _catalog_log(FATAL_ERROR "Invalid package name: ${PACKAGE_NAME}")
  endif()
  _catalog_add_recipe(${PACKAGE_NAME} ${RECIPE_SOURCE})
endfunction()

function(_catalog_impl_add_dependency)
  set(POSITIONALS "")
  set(LINK_SCOPE "")
  set(REQ_TYPE "")
  set(VERSION_SPEC "")
  set(OPTION_OVERRIDES "")
  set(PATCH_OVERRIDES "")
  set(FORCE_SOURCE FALSE)

  set(MODE "")

  foreach(ARG ${ARGN})
    if(ARG STREQUAL "VERSION")
      set(MODE "VERSION")
    elseif(ARG STREQUAL "OPTIONS")
      set(MODE "OPTIONS")
      set(FORCE_SOURCE TRUE)
    elseif(ARG STREQUAL "SOURCE_OPTIONS")
      set(MODE "OPTIONS")
    elseif(ARG STREQUAL "PATCH")
      set(MODE "PATCH")
      set(FORCE_SOURCE TRUE)
    elseif(ARG STREQUAL "SOURCE_PATCH")
      set(MODE "PATCH")
    elseif(ARG STREQUAL "PUBLIC" OR ARG STREQUAL "PRIVATE" OR ARG STREQUAL "INTERFACE")
      set(MODE "")
      set(LINK_SCOPE "${ARG}")
    elseif(ARG STREQUAL "STATIC" OR ARG STREQUAL "SHARED" OR ARG STREQUAL "PREFER_STATIC" OR ARG STREQUAL "PREFER_SHARED")
      set(MODE "")
      set(REQ_TYPE "${ARG}")
    elseif(MODE STREQUAL "VERSION")
      set(VERSION_SPEC "${ARG}")
      set(MODE "")
    elseif(MODE STREQUAL "OPTIONS")
      list(APPEND OPTION_OVERRIDES "${ARG}")
    elseif(MODE STREQUAL "PATCH")
      list(APPEND PATCH_OVERRIDES "${ARG}")
    elseif(ARG MATCHES "^[0-9]+(\\.[0-9]+)*" OR ARG MATCHES "^(>=|<=|>|<|=|==|\\^|~)" OR ARG MATCHES "\\.\\.\\.")
      set(VERSION_SPEC "${ARG}")
    else()
      list(APPEND POSITIONALS "${ARG}")
    endif()
  endforeach()

  list(LENGTH POSITIONALS POS_LEN)
  if(POS_LEN EQUAL 0)
    _catalog_log(FATAL_ERROR "add_dependency: missing package name")
  elseif(POS_LEN EQUAL 1)
    set(TARGET_NAME "")
    list(GET POSITIONALS 0 PACKAGE_NAME)
  else()
    list(GET POSITIONALS 0 TARGET_NAME)
    list(GET POSITIONALS 1 PACKAGE_NAME)
  endif()
  
  _catalog_valid_target_name("${PACKAGE_NAME}" VALID_PKG)
  if(NOT VALID_PKG)
    _catalog_log(FATAL_ERROR "Invalid package name: ${PACKAGE_NAME}")
  endif()
  
  if(NOT TARGET_NAME STREQUAL "")
    _catalog_valid_target_name("${TARGET_NAME}" VALID_TARGET)
    if(NOT VALID_TARGET)
      _catalog_log(FATAL_ERROR "Invalid target name: ${TARGET_NAME}")
    endif()
  endif()
  
  _catalog_resolve_dependency("${PACKAGE_NAME}" "${REQ_TYPE}" "${VERSION_SPEC}" "${OPTION_OVERRIDES}" "${PATCH_OVERRIDES}" "${FORCE_SOURCE}")
  
  if(NOT TARGET_NAME STREQUAL "")
    if(TARGET ${TARGET_NAME})
      if(LINK_SCOPE STREQUAL "")
        get_target_property(TARGET_TYPE ${TARGET_NAME} TYPE)
        if(TARGET_TYPE STREQUAL "INTERFACE_LIBRARY")
          set(LINK_SCOPE "INTERFACE")
        else()
          set(LINK_SCOPE "PRIVATE")
        endif()
      endif()
      target_link_libraries(${TARGET_NAME} ${LINK_SCOPE} deps::${PACKAGE_NAME})
    else()
      _catalog_log(WARNING "Target does not exist: ${TARGET_NAME}")
    endif()
  endif()
endfunction()

function(_catalog_define_alias ALIAS_NAME TARGET_FUNC)
  if(NOT COMMAND "${ALIAS_NAME}")
    set(_ARG_CHECKS "")
    foreach(_I RANGE 0 63)
      string(APPEND _ARG_CHECKS "\n  if(${_I} LESS \${ARGC})\n    string(APPEND _ALIAS_CALL \" [==[\${ARGV${_I}}]==]\")\n  endif()")
    endforeach()

    cmake_language(EVAL CODE "
macro(${ALIAS_NAME})
  set(_ALIAS_CALL \"${TARGET_FUNC}(\")${_ARG_CHECKS}
  string(APPEND _ALIAS_CALL \")\")
  cmake_language(EVAL CODE \"\${_ALIAS_CALL}\")
  unset(_ALIAS_CALL)
endmacro()
")
  endif()
endfunction()

function(_catalog_setup_aliases)
  set(FUNCTION_MAPPINGS
    "repo:_catalog_impl_repo"
    "add_recipe:_catalog_impl_add_recipe"
    "add_dependency:_catalog_impl_add_dependency"
    "add_dep:_catalog_impl_add_dependency"
    "import_source:_catalog_impl_import_source"
    "repo_file:_catalog_impl_repo_file"
    "format_pkgconfig_req:_catalog_format_pkgconfig_req"
    "is_var_defined:_catalog_is_var_defined"
    "get_var:_catalog_get_var"
    "set_var:_catalog_set_var"
  )

  set(PREFIXES "catalog_" "cl_")

  if(DEFINED CATALOG_PREFIX AND NOT CATALOG_PREFIX STREQUAL "")
    string(TOLOWER "${CATALOG_PREFIX}" _LOW_PREF)
    if(NOT _LOW_PREF MATCHES "_$")
      string(APPEND _LOW_PREF "_")
    endif()
    list(FIND PREFIXES "${_LOW_PREF}" _P_IDX)
    if(_P_IDX EQUAL -1)
      list(APPEND PREFIXES "${_LOW_PREF}")
    endif()
  endif()

  foreach(MAP ${FUNCTION_MAPPINGS})
    string(REPLACE ":" ";" MAP_PAIR "${MAP}")
    list(GET MAP_PAIR 0 BASE_NAME)
    list(GET MAP_PAIR 1 IMPL_NAME)

    foreach(PREF ${PREFIXES})
      _catalog_define_alias("${PREF}${BASE_NAME}" "${IMPL_NAME}")
    endforeach()
  endforeach()
endfunction()

_catalog_setup_aliases()
