include(${CMAKE_CURRENT_LIST_DIR}/internal/utils.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/internal/recipe.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/internal/resolve.cmake)

function(catalog_repo REPO_SOURCE)
  _catalog_load_repo_meta(${REPO_SOURCE})
endfunction()

function(catalog_add_recipe PACKAGE_NAME RECIPE_SOURCE)
  _catalog_valid_target_name("${PACKAGE_NAME}" VALID_PKG)
  if(NOT VALID_PKG)
    _catalog_log(FATAL_ERROR "Invalid package name: ${PACKAGE_NAME}")
  endif()
  _catalog_add_recipe(${PACKAGE_NAME} ${RECIPE_SOURCE})
endfunction()

function(catalog_add_dependency FIRST_ARG)
  set(TARGET_NAME "")
  set(PACKAGE_NAME "${FIRST_ARG}")
  
  if(ARGC GREATER 1)
    set(TARGET_NAME "${FIRST_ARG}")
    set(PACKAGE_NAME "${ARGV1}")
  endif()
  
  _catalog_valid_target_name("${PACKAGE_NAME}" VALID_PKG)
  if(NOT VALID_PKG)
    _catalog_log(FATAL_ERROR "Invalid package name: ${PACKAGE_NAME}")
  endif()
  
  if(NOT TARGET_NAME STREQUAL "")
    _catalog_valid_target_name("${TARGET_NAME}" VALID_TARGET)
    if(NOT VALID_TARGET)
      _catalog_log(FATAL_ERROR "Invalid target name: ${TARGET_NAME}")
    endif()
  endif()
  
  _catalog_resolve_dependency(${PACKAGE_NAME})
  
  if(NOT TARGET_NAME STREQUAL "")
    if(TARGET ${TARGET_NAME})
      get_target_property(TARGET_TYPE ${TARGET_NAME} TYPE)
      if(TARGET_TYPE STREQUAL "INTERFACE_LIBRARY")
        set(LINK_SCOPE "INTERFACE")
      else()
        set(LINK_SCOPE "PRIVATE")
      endif()
      target_link_libraries(${TARGET_NAME} ${LINK_SCOPE} deps::${PACKAGE_NAME})
    else()
      _catalog_log(WARNING "Target does not exist: ${TARGET_NAME}")
    endif()
  endif()
endfunction()
