set(_CATALOG_REPOS "" CACHE INTERNAL "Loaded repositories")
set(_CATALOG_DIRECT_RECIPES "" CACHE INTERNAL "Direct recipe paths")
set(_CATALOG_ALL_RECIPES "" CACHE INTERNAL "All registered recipes")

function(_catalog_load_repo_meta REPO_SOURCE)
  _catalog_resolve_repo_url(${REPO_SOURCE} RESOLVED_URL REPO_TYPE REPO_BASE REPO_NAME)
  _catalog_log_verbose("Loading repository ${REPO_NAME} (${REPO_TYPE}) from ${RESOLVED_URL}")
  
  _catalog_load_recipe(${RESOLVED_URL} REPO_FILE)
  
  unset(CATALOG_RECIPES)
  unset(CL_RECIPES)
  include(${REPO_FILE})
  
  _catalog_get_var("RECIPES" CATALOG_RECIPES_VAL)
  if("${CATALOG_RECIPES_VAL}" STREQUAL "")
    _catalog_log(FATAL_ERROR "Repository meta.cmake did not define CATALOG_RECIPES")
  endif()
  
  if(REPO_TYPE STREQUAL "local")
    _catalog_set_var("REPO_DIR" "${REPO_BASE}")
  else()
    _catalog_set_var("REPO_DIR" "")
  endif()
  _catalog_set_var("REPO_NAME" "${REPO_NAME}")
  _catalog_set_var("REPO_TYPE" "${REPO_TYPE}")
  
  set(NEW_RECIPES "")
  foreach(RECIPE ${CATALOG_RECIPES_VAL})
    if(RECIPE MATCHES "^([^:]+):(.+)$")
      set(RECIPE_NAME "${CMAKE_MATCH_1}")
      set(RECIPE_PATH "${CMAKE_MATCH_2}")
      
      if(RECIPE_PATH MATCHES "^https?://" OR RECIPE_PATH MATCHES "^/")
        set(RESOLVED_RECIPE "${RECIPE_PATH}")
      else()
        set(RESOLVED_RECIPE "${REPO_BASE}/${RECIPE_PATH}")
      endif()
      
      list(APPEND NEW_RECIPES "${RECIPE_NAME}:${RESOLVED_RECIPE}")
    endif()
  endforeach()
  
  set(_CATALOG_ALL_RECIPES "${_CATALOG_ALL_RECIPES};${NEW_RECIPES}" CACHE INTERNAL "All registered recipes")
  _catalog_set_var("RECIPES" "${CATALOG_RECIPES_VAL}")
  
  list(APPEND _CATALOG_REPOS "${RESOLVED_URL}")
  set(_CATALOG_REPOS "${_CATALOG_REPOS}" CACHE INTERNAL "Loaded repositories")
endfunction()

function(_catalog_add_recipe PACKAGE_NAME RECIPE_SOURCE)
  _catalog_resolve_recipe_url(${RECIPE_SOURCE} RESOLVED_URL)
  list(APPEND _CATALOG_DIRECT_RECIPES "${PACKAGE_NAME}:${RESOLVED_URL}")
  set(_CATALOG_DIRECT_RECIPES "${_CATALOG_DIRECT_RECIPES}" CACHE INTERNAL "Direct recipe paths")
endfunction()

function(_catalog_find_recipe PACKAGE_NAME RECIPE_PATH_VAR)
  foreach(RECIPE ${_CATALOG_DIRECT_RECIPES})
    if(RECIPE MATCHES "^${PACKAGE_NAME}:")
      string(REGEX REPLACE "^${PACKAGE_NAME}:" "" RECIPE_PATH "${RECIPE}")
      set(${RECIPE_PATH_VAR} "${RECIPE_PATH}" PARENT_SCOPE)
      return()
    endif()
  endforeach()
  
  foreach(RECIPE ${_CATALOG_ALL_RECIPES})
    if(RECIPE MATCHES "^${PACKAGE_NAME}:")
      string(REGEX REPLACE "^${PACKAGE_NAME}:" "" RECIPE_PATH "${RECIPE}")
      set(${RECIPE_PATH_VAR} "${RECIPE_PATH}" PARENT_SCOPE)
      return()
    endif()
  endforeach()
  
  if(NOT _CATALOG_ALL_RECIPES AND NOT _CATALOG_DIRECT_RECIPES)
    _catalog_log(FATAL_ERROR "No recipes or repositories loaded. Use catalog_repo() or catalog_add_recipe() first.")
  else()
    _catalog_log(FATAL_ERROR "Recipe not found: ${PACKAGE_NAME}")
  endif()
endfunction()

function(_catalog_alias_target PACKAGE_NAME)
  if(TARGET deps::${PACKAGE_NAME})
    return()
  endif()

  _catalog_find_target_alias(${PACKAGE_NAME} TARGET_NAME)
  
  if(TARGET_NAME)
    add_library(deps::${PACKAGE_NAME} ALIAS ${TARGET_NAME})
    _catalog_log_verbose("Created alias deps::${PACKAGE_NAME} -> ${TARGET_NAME}")
    return()
  endif()
  
  _catalog_log_verbose("No target found for ${PACKAGE_NAME} in this stage")
endfunction()

function(_catalog_execute_stage PACKAGE_NAME STAGE)
  if(TARGET deps::${PACKAGE_NAME})
    return()
  endif()

  set(RECIPE_FUNC "_recipe_${PACKAGE_NAME}_${STAGE}")
  
  if(COMMAND ${RECIPE_FUNC})
    _catalog_log_verbose("Executing ${STAGE} stage for ${PACKAGE_NAME}")
    cmake_language(CALL ${RECIPE_FUNC})
  endif()
  
  _catalog_alias_target(${PACKAGE_NAME})
endfunction()

function(_catalog_prompt_install PACKAGE_NAME)
  set(_CATALOG_FAILED_PACKAGE_STAGE FALSE PARENT_SCOPE)

  set(IS_INTERACTIVE TRUE)
  _catalog_is_var_defined("NON_INTERACTIVE" HAS_NON_INTERACTIVE ENV)
  if(DEFINED ENV{CI} OR HAS_NON_INTERACTIVE)
    set(IS_INTERACTIVE FALSE)
  endif()
  
  if(NOT IS_INTERACTIVE)
    _catalog_log_verbose("Non-interactive environment detected, skipping package installation prompt.")
    set(_CATALOG_FAILED_PACKAGE_STAGE TRUE PARENT_SCOPE)
    return()
  endif()
  
  _catalog_get_var("PACKAGE_MANAGER" CATALOG_PACKAGE_MANAGER ENV)
  _catalog_get_var("PACKAGE_NAME" CATALOG_PACKAGE_NAME)
  
  _catalog_log(STATUS "Install ${PACKAGE_NAME} using ${CATALOG_PACKAGE_MANAGER}? [y/n]")
  
  execute_process(
    COMMAND sh -c "read -t 30 -n 1 -p '' REPLY; echo \$REPLY; echo"
    OUTPUT_VARIABLE USER_INPUT
    OUTPUT_STRIP_TRAILING_WHITESPACE
    TIMEOUT 30
  )
  
  if(USER_INPUT MATCHES "^[yY]$")
    _catalog_log(STATUS "Installing ${PACKAGE_NAME}...")
    
    if(CATALOG_PACKAGE_MANAGER STREQUAL "apt")
      execute_process(COMMAND sudo apt-get install -y ${CATALOG_PACKAGE_NAME})
    elseif(CATALOG_PACKAGE_MANAGER STREQUAL "pacman")
      execute_process(COMMAND sudo pacman -S --noconfirm ${CATALOG_PACKAGE_NAME})
    elseif(CATALOG_PACKAGE_MANAGER STREQUAL "brew")
      execute_process(COMMAND brew install ${CATALOG_PACKAGE_NAME})
    elseif(CATALOG_PACKAGE_MANAGER STREQUAL "yum")
      execute_process(COMMAND sudo yum install -y ${CATALOG_PACKAGE_NAME})
    elseif(CATALOG_PACKAGE_MANAGER STREQUAL "apk")
      execute_process(COMMAND sudo apk add ${CATALOG_PACKAGE_NAME})
    elseif(CATALOG_PACKAGE_MANAGER STREQUAL "zypper")
      execute_process(COMMAND sudo zypper install -y ${CATALOG_PACKAGE_NAME})
    elseif(CATALOG_PACKAGE_MANAGER STREQUAL "emerge")
      execute_process(COMMAND sudo emerge ${CATALOG_PACKAGE_NAME})
    else()
      _catalog_log_verbose("Unknown package manager detected, trying remaining stages...")
      set(_CATALOG_FAILED_PACKAGE_STAGE TRUE PARENT_SCOPE)
      return()
    endif()
    
    _catalog_log_verbose("Installation command executed.")
  else()
    _catalog_log_verbose(STATUS "${PACKAGE_NAME}: package install skipped, trying remaining stages...")
    set(_CATALOG_FAILED_PACKAGE_STAGE TRUE PARENT_SCOPE)
  endif()
endfunction()

function(_catalog_resolve_dependency PACKAGE_NAME)
  if(TARGET deps::${PACKAGE_NAME})
    _catalog_log_verbose("${PACKAGE_NAME}: already resolved, skipping")
    return()
  endif()
  
  set(REQ_TYPE "")
  if(ARGC GREATER 1)
    set(REQ_TYPE "${ARGV1}")
  endif()

  if(REQ_TYPE STREQUAL "")
    _catalog_get_var("${PACKAGE_NAME}_REQ_TYPE" REQ_TYPE)
    if(REQ_TYPE STREQUAL "")
      _catalog_get_var("REQ_TYPE" REQ_TYPE)
    endif()
  endif()

  if(REQ_TYPE STREQUAL "")
    _catalog_is_var_defined("${PACKAGE_NAME}_STATIC" HAS_PKG_STATIC)
    _catalog_is_var_defined("STATIC" HAS_STATIC)
    _catalog_is_var_defined("${PACKAGE_NAME}_SHARED" HAS_PKG_SHARED)
    _catalog_is_var_defined("SHARED" HAS_SHARED)
    _catalog_is_var_defined("${PACKAGE_NAME}_PREFER_STATIC" HAS_PKG_PSTATIC)
    _catalog_is_var_defined("PREFER_STATIC" HAS_PSTATIC)
    _catalog_is_var_defined("${PACKAGE_NAME}_PREFER_SHARED" HAS_PKG_PSHARED)
    _catalog_is_var_defined("PREFER_SHARED" HAS_PSHARED)

    if(HAS_PKG_STATIC OR HAS_STATIC)
      set(REQ_TYPE "STATIC")
    elseif(HAS_PKG_SHARED OR HAS_SHARED)
      set(REQ_TYPE "SHARED")
    elseif(HAS_PKG_PSTATIC OR HAS_PSTATIC)
      set(REQ_TYPE "PREFER_STATIC")
    elseif(HAS_PKG_PSHARED OR HAS_PSHARED)
      set(REQ_TYPE "PREFER_SHARED")
    endif()
  endif()

  _catalog_set_var("REQ_TYPE" "${REQ_TYPE}")
  _catalog_set_var("${PACKAGE_NAME}_REQ_TYPE" "${REQ_TYPE}")

  set(CATALOG_STATIC FALSE)
  set(CATALOG_SHARED FALSE)
  set(CATALOG_PREFER_STATIC FALSE)
  set(CATALOG_PREFER_SHARED FALSE)
  set(CATALOG_REQUIRE_STATIC FALSE)
  set(CATALOG_REQUIRE_SHARED FALSE)

  if(REQ_TYPE STREQUAL "STATIC")
    set(CATALOG_STATIC TRUE)
    set(CATALOG_REQUIRE_STATIC TRUE)
  elseif(REQ_TYPE STREQUAL "SHARED")
    set(CATALOG_SHARED TRUE)
    set(CATALOG_REQUIRE_SHARED TRUE)
  elseif(REQ_TYPE STREQUAL "PREFER_STATIC")
    set(CATALOG_STATIC TRUE)
    set(CATALOG_PREFER_STATIC TRUE)
  elseif(REQ_TYPE STREQUAL "PREFER_SHARED")
    set(CATALOG_SHARED TRUE)
    set(CATALOG_PREFER_SHARED TRUE)
  endif()

  _catalog_set_var("STATIC" "${CATALOG_STATIC}")
  _catalog_set_var("SHARED" "${CATALOG_SHARED}")
  _catalog_set_var("PREFER_STATIC" "${CATALOG_PREFER_STATIC}")
  _catalog_set_var("PREFER_SHARED" "${CATALOG_PREFER_SHARED}")
  _catalog_set_var("REQUIRE_STATIC" "${CATALOG_REQUIRE_STATIC}")
  _catalog_set_var("REQUIRE_SHARED" "${CATALOG_REQUIRE_SHARED}")
  
  _catalog_set_var("${PACKAGE_NAME}_STATIC" "${CATALOG_STATIC}")
  _catalog_set_var("${PACKAGE_NAME}_SHARED" "${CATALOG_SHARED}")
  _catalog_set_var("${PACKAGE_NAME}_PREFER_STATIC" "${CATALOG_PREFER_STATIC}")
  _catalog_set_var("${PACKAGE_NAME}_PREFER_SHARED" "${CATALOG_PREFER_SHARED}")
  _catalog_set_var("${PACKAGE_NAME}_REQUIRE_STATIC" "${CATALOG_REQUIRE_STATIC}")
  _catalog_set_var("${PACKAGE_NAME}_REQUIRE_SHARED" "${CATALOG_REQUIRE_SHARED}")

  _catalog_find_recipe(${PACKAGE_NAME} RECIPE_PATH)
  _catalog_load_recipe(${RECIPE_PATH} RECIPE_FILE)
  include(${RECIPE_FILE})
  
  set(STAGES toolchain system package prebuilt source)
  
  _catalog_get_var("STAGES" CATALOG_STAGES_VAL)
  if(NOT "${CATALOG_STAGES_VAL}" STREQUAL "")
    set(STAGES ${CATALOG_STAGES_VAL})
  endif()
  
  _catalog_get_var("${PACKAGE_NAME}_STAGES" PKG_STAGES_VAL)
  if(NOT "${PKG_STAGES_VAL}" STREQUAL "")
    set(STAGES ${PKG_STAGES_VAL})
  endif()
  
  set(FORCED_STAGE "")
  foreach(S ${STAGES})
    _catalog_get_var("FORCE_${S}_${PACKAGE_NAME}" FORCE_VAL)
    if(FORCE_VAL)
      set(FORCED_STAGE "${S}")
      break()
    endif()
  endforeach()
  
  if(NOT FORCED_STAGE STREQUAL "")
    set(STAGES "${FORCED_STAGE}")
  endif()
  
  foreach(STAGE ${STAGES})
    _catalog_is_var_defined("DISABLE_${STAGE}_${PACKAGE_NAME}" IS_DISABLED)
    if(IS_DISABLED)
      continue()
    endif()
    
    if(STAGE STREQUAL "package")
      _catalog_is_var_defined("DISABLE_system_${PACKAGE_NAME}" IS_SYS_DISABLED)
      if(IS_SYS_DISABLED)
        continue()
      endif()

      set(RECIPE_FUNC "_recipe_${PACKAGE_NAME}_package")
      if(COMMAND ${RECIPE_FUNC})
        _catalog_log_verbose("Querying package stage for ${PACKAGE_NAME}")
        cmake_language(CALL ${RECIPE_FUNC})
        
        _catalog_get_var("PACKAGE_NAME" CATALOG_PACKAGE_NAME)
        _catalog_get_var("PACKAGE_MANAGER" CATALOG_PACKAGE_MANAGER ENV)
        if(NOT "${CATALOG_PACKAGE_NAME}" STREQUAL "" AND NOT "${CATALOG_PACKAGE_MANAGER}" STREQUAL "")
          _catalog_prompt_install(${PACKAGE_NAME})
          if(_CATALOG_FAILED_PACKAGE_STAGE)
            continue()
          endif()

          _catalog_execute_stage(${PACKAGE_NAME} system)
          
          if(TARGET deps::${PACKAGE_NAME})
            _catalog_log_verbose(STATUS "${PACKAGE_NAME}: resolved via package manager")
            return()
          endif()
        endif()
        unset(CATALOG_PACKAGE_NAME)
        unset(CL_PACKAGE_NAME)
      endif()
    else()
      _catalog_execute_stage(${PACKAGE_NAME} ${STAGE})
      
      if(TARGET deps::${PACKAGE_NAME})
        _catalog_log(STATUS "${PACKAGE_NAME}: resolved via ${STAGE}")
        return()
      endif()
    endif()
  endforeach()
  
  _catalog_log(FATAL_ERROR "Failed to resolve dependency: ${PACKAGE_NAME}")
endfunction()
