macro(_catalog_log LEVEL MESSAGE)
  message(${LEVEL} "[Catalog] ${MESSAGE}")
endmacro()

macro(_catalog_get_var_prefixes RESULT_LIST_VAR)
  set(${RESULT_LIST_VAR} "CATALOG_" "CL_")
  if(DEFINED CATALOG_PREFIX AND NOT CATALOG_PREFIX STREQUAL "")
    string(TOUPPER "${CATALOG_PREFIX}" _UP_PREF)
    if(NOT _UP_PREF MATCHES "_$")
      string(APPEND _UP_PREF "_")
    endif()
    list(FIND ${RESULT_LIST_VAR} "${_UP_PREF}" _PREF_IDX)
    if(_PREF_IDX EQUAL -1)
      list(APPEND ${RESULT_LIST_VAR} "${_UP_PREF}")
    endif()
  endif()
endmacro()

function(_catalog_is_var_defined SUFFIX RESULT_VAR)
  set(options ENV)
  cmake_parse_arguments(IS_DEF "${options}" "" "" ${ARGN})

  _catalog_get_var_prefixes(_PREFIXES)
  foreach(_P ${_PREFIXES})
    if(DEFINED "${_P}${SUFFIX}")
      set(${RESULT_VAR} TRUE PARENT_SCOPE)
      return()
    endif()
  endforeach()

  if(IS_DEF_ENV)
    foreach(_P ${_PREFIXES})
      string(REGEX REPLACE "_$" "" _ENV_P "${_P}")
      if(DEFINED ENV{${_ENV_P}_${SUFFIX}})
        set(${RESULT_VAR} TRUE PARENT_SCOPE)
        return()
      endif()
    endforeach()
  endif()

  set(${RESULT_VAR} FALSE PARENT_SCOPE)
endfunction()

function(_catalog_get_var SUFFIX RESULT_VAR)
  set(options ENV)
  cmake_parse_arguments(GET_VAR "${options}" "" "" ${ARGN})

  _catalog_get_var_prefixes(_PREFIXES)
  foreach(_P ${_PREFIXES})
    if(DEFINED "${_P}${SUFFIX}")
      set(${RESULT_VAR} "${${_P}${SUFFIX}}" PARENT_SCOPE)
      return()
    endif()
  endforeach()

  if(GET_VAR_ENV)
    foreach(_P ${_PREFIXES})
      string(REGEX REPLACE "_$" "" _ENV_P "${_P}")
      if(DEFINED ENV{${_ENV_P}_${SUFFIX}})
        set(${RESULT_VAR} "$ENV{${_ENV_P}_${SUFFIX}}" PARENT_SCOPE)
        return()
      endif()
    endforeach()
  endif()

  set(${RESULT_VAR} "" PARENT_SCOPE)
endfunction()

macro(_catalog_set_var SUFFIX VALUE)
  _catalog_get_var_prefixes(_PREFIXES)
  foreach(_P ${_PREFIXES})
    set("${_P}${SUFFIX}" "${VALUE}")
    set("${_P}${SUFFIX}" "${VALUE}" PARENT_SCOPE)
  endforeach()
endmacro()

function(_catalog_extract_version RAW_STR RESULT_VAR)
  if(RAW_STR MATCHES "v?([0-9]+(\\.[0-9]+)*([-._]?[a-zA-Z0-9]+)?)")
    set(${RESULT_VAR} "${CMAKE_MATCH_1}" PARENT_SCOPE)
  else()
    set(${RESULT_VAR} "" PARENT_SCOPE)
  endif()
endfunction()

function(_catalog_parse_version VER_STR NUM_VAR TAG_WEIGHT_VAR SUB_NUM_VAR)
  if(VER_STR MATCHES "^v?([0-9]+(\\.[0-9]+)*)([-._]?([a-zA-Z]+)[-._]?([0-9]+)?)?")
    set(NUM_PART "${CMAKE_MATCH_1}")
    set(TAG_NAME "${CMAKE_MATCH_4}")
    set(SUB_NUM "${CMAKE_MATCH_5}")
  else()
    set(NUM_PART "${VER_STR}")
    set(TAG_NAME "")
    set(SUB_NUM "")
  endif()

  string(TOLOWER "${TAG_NAME}" TAG_LOWER)

  if(TAG_LOWER STREQUAL "dev" OR TAG_LOWER STREQUAL "nightly")
    set(WEIGHT 10)
  elseif(TAG_LOWER STREQUAL "alpha" OR TAG_LOWER STREQUAL "a")
    set(WEIGHT 20)
  elseif(TAG_LOWER STREQUAL "beta" OR TAG_LOWER STREQUAL "b")
    set(WEIGHT 30)
  elseif(TAG_LOWER STREQUAL "pre" OR TAG_LOWER STREQUAL "prerelease" OR TAG_LOWER STREQUAL "pre-release" OR TAG_LOWER STREQUAL "preview")
    set(WEIGHT 40)
  elseif(TAG_LOWER STREQUAL "rc" OR TAG_LOWER STREQUAL "release-candidate" OR TAG_LOWER STREQUAL "release_candidate" OR TAG_LOWER STREQUAL "c")
    set(WEIGHT 50)
  elseif(TAG_LOWER STREQUAL "patch" OR TAG_LOWER STREQUAL "pl" OR TAG_LOWER STREQUAL "p" OR TAG_LOWER STREQUAL "post")
    set(WEIGHT 110)
  else()
    set(WEIGHT 100)
  endif()

  if(SUB_NUM STREQUAL "")
    set(SUB_NUM 0)
  endif()

  set(${NUM_VAR} "${NUM_PART}" PARENT_SCOPE)
  set(${TAG_WEIGHT_VAR} "${WEIGHT}" PARENT_SCOPE)
  set(${SUB_NUM_VAR} "${SUB_NUM}" PARENT_SCOPE)
endfunction()

function(_catalog_compare_versions VER1 OP VER2 RESULT_VAR)
  _catalog_parse_version("${VER1}" NUM1 TAG1 SUB1)
  _catalog_parse_version("${VER2}" NUM2 TAG2 SUB2)

  set(CMP 0)

  if(NUM1 VERSION_LESS NUM2)
    set(CMP -1)
  elseif(NUM1 VERSION_GREATER NUM2)
    set(CMP 1)
  else()
    if(TAG1 LESS TAG2)
      set(CMP -1)
    elseif(TAG1 GREATER TAG2)
      set(CMP 1)
    else()
      if(SUB1 LESS SUB2)
        set(CMP -1)
      elseif(SUB1 GREATER SUB2)
        set(CMP 1)
      else()
        set(CMP 0)
      endif()
    endif()
  endif()

  if(OP STREQUAL "=" OR OP STREQUAL "==" OR OP STREQUAL "EQUAL")
    if(CMP EQUAL 0)
      set(${RESULT_VAR} TRUE PARENT_SCOPE)
    else()
      set(${RESULT_VAR} FALSE PARENT_SCOPE)
    endif()
  elseif(OP STREQUAL "<" OR OP STREQUAL "LESS")
    if(CMP LESS 0)
      set(${RESULT_VAR} TRUE PARENT_SCOPE)
    else()
      set(${RESULT_VAR} FALSE PARENT_SCOPE)
    endif()
  elseif(OP STREQUAL "<=" OR OP STREQUAL "LESS_EQUAL")
    if(CMP LESS 0 OR CMP EQUAL 0)
      set(${RESULT_VAR} TRUE PARENT_SCOPE)
    else()
      set(${RESULT_VAR} FALSE PARENT_SCOPE)
    endif()
  elseif(OP STREQUAL ">" OR OP STREQUAL "GREATER")
    if(CMP GREATER 0)
      set(${RESULT_VAR} TRUE PARENT_SCOPE)
    else()
      set(${RESULT_VAR} FALSE PARENT_SCOPE)
    endif()
  elseif(OP STREQUAL ">=" OR OP STREQUAL "GREATER_EQUAL")
    if(CMP GREATER 0 OR CMP EQUAL 0)
      set(${RESULT_VAR} TRUE PARENT_SCOPE)
    else()
      set(${RESULT_VAR} FALSE PARENT_SCOPE)
    endif()
  else()
    set(${RESULT_VAR} FALSE PARENT_SCOPE)
  endif()
endfunction()

function(_catalog_sort_versions VERSIONS_VAR)
  set(L "${${VERSIONS_VAR}}")
  list(LENGTH L LEN)
  if(LEN LESS 2)
    return()
  endif()

  math(EXPR OUTER_LIMIT "${LEN} - 1")
  foreach(I RANGE 0 ${OUTER_LIMIT})
    math(EXPR INNER_LIMIT "${LEN} - 2")
    if(INNER_LIMIT GREATER_EQUAL 0)
      foreach(J RANGE 0 ${INNER_LIMIT})
        math(EXPR NEXT_J "${J} + 1")
        list(GET L ${J} V1)
        list(GET L ${NEXT_J} V2)
        _catalog_compare_versions("${V1}" ">" "${V2}" IS_GREATER)
        if(IS_GREATER)
          list(SET L ${J} "${V2}")
          list(SET L ${NEXT_J} "${V1}")
        endif()
      endforeach()
    endif()
  endforeach()
  set(${VERSIONS_VAR} "${L}" PARENT_SCOPE)
endfunction()

function(_catalog_version_satisfies TEST_VER SPEC_STR RESULT_VAR)
  if(SPEC_STR STREQUAL "" OR TEST_VER STREQUAL "")
    set(${RESULT_VAR} TRUE PARENT_SCOPE)
    return()
  endif()

  string(REPLACE "," ";" SPEC_LIST "${SPEC_STR}")
  foreach(SPEC ${SPEC_LIST})
    string(STRIP "${SPEC}" SPEC)
    set(SATISFIED FALSE)

    if(SPEC MATCHES "^v?([^\\.\\s]+(\\.[^\\.\\s]+)*)\\s*(\\.\\.|-)\\s*v?([^\\.\\s]+(\\.[^\\.\\s]+)*)$")
      set(MIN_V "${CMAKE_MATCH_1}")
      set(MAX_V "${CMAKE_MATCH_4}")
      _catalog_compare_versions("${TEST_VER}" ">=" "${MIN_V}" SAT_MIN)
      _catalog_compare_versions("${TEST_VER}" "<=" "${MAX_V}" SAT_MAX)
      if(SAT_MIN AND SAT_MAX)
        set(SATISFIED TRUE)
      endif()
    elseif(SPEC MATCHES "^\\^v?([0-9]+)(\\.[0-9]+)*(.*)")
      set(MAJOR "${CMAKE_MATCH_1}")
      set(MIN_V "${SPEC}")
      string(REGEX REPLACE "^\\^v?" "" MIN_V "${MIN_V}")
      math(EXPR NEXT_MAJOR "${MAJOR} + 1")
      set(MAX_V "${NEXT_MAJOR}.0.0")
      _catalog_compare_versions("${TEST_VER}" ">=" "${MIN_V}" SAT_MIN)
      _catalog_compare_versions("${TEST_VER}" "<" "${MAX_V}" SAT_MAX)
      if(SAT_MIN AND SAT_MAX)
        set(SATISFIED TRUE)
      endif()
    elseif(SPEC MATCHES "^~v?([0-9]+)\\.([0-9]+)(.*)")
      set(MAJOR "${CMAKE_MATCH_1}")
      set(MINOR "${CMAKE_MATCH_2}")
      set(MIN_V "${SPEC}")
      string(REGEX REPLACE "^~v?" "" MIN_V "${MIN_V}")
      math(EXPR NEXT_MINOR "${MINOR} + 1")
      set(MAX_V "${MAJOR}.${NEXT_MINOR}.0")
      _catalog_compare_versions("${TEST_VER}" ">=" "${MIN_V}" SAT_MIN)
      _catalog_compare_versions("${TEST_VER}" "<" "${MAX_V}" SAT_MAX)
      if(SAT_MIN AND SAT_MAX)
        set(SATISFIED TRUE)
      endif()
    elseif(SPEC MATCHES "^(>=|<=|>|<|=|==)\\s*v?([0-9]+(\\.[0-9]+)*([-._]?[a-zA-Z0-9]+)?)")
      set(OP "${CMAKE_MATCH_1}")
      set(TGT_V "${CMAKE_MATCH_2}")
      _catalog_compare_versions("${TEST_VER}" "${OP}" "${TGT_V}" SATISFIED)
    elseif(SPEC MATCHES "^v?([0-9]+(\\.[0-9]+)*([-._]?[a-zA-Z0-9]+)?)")
      set(TGT_V "${CMAKE_MATCH_1}")
      _catalog_compare_versions("${TEST_VER}" ">=" "${TGT_V}" SATISFIED)
    else()
      set(SATISFIED TRUE)
    endif()

    if(NOT SATISFIED)
      set(${RESULT_VAR} FALSE PARENT_SCOPE)
      return()
    endif()
  endforeach()

  set(${RESULT_VAR} TRUE PARENT_SCOPE)
endfunction()

function(_catalog_format_pkgconfig_req PKG_NAME REQ_STR RESULT_LIST_VAR)
  if(REQ_STR STREQUAL "")
    set(${RESULT_LIST_VAR} "${PKG_NAME}" PARENT_SCOPE)
    return()
  endif()

  string(STRIP "${REQ_STR}" REQ_STR)

  if(REQ_STR MATCHES "^(=|==)\\s*(.+)")
    set(${RESULT_LIST_VAR} "${PKG_NAME}=${CMAKE_MATCH_2}" PARENT_SCOPE)
  elseif(REQ_STR MATCHES "^(>=|<=|>|<)\\s*(.+)")
    set(${RESULT_LIST_VAR} "${PKG_NAME}${REQ_STR}" PARENT_SCOPE)
  elseif(REQ_STR MATCHES "^v?([^\\.\\s]+(\\.[^\\.\\s]+)*)\\s*(\\.\\.|-)\\s*v?([^\\.\\s]+(\\.[^\\.\\s]+)*)$")
    set(MIN_V "${CMAKE_MATCH_1}")
    set(MAX_V "${CMAKE_MATCH_4}")
    set(${RESULT_LIST_VAR} "${PKG_NAME}>=${MIN_V}" "${PKG_NAME}<=${MAX_V}" PARENT_SCOPE)
  elseif(REQ_STR MATCHES "^v?([0-9]+(\\.[0-9]+)*([-._]?[a-zA-Z0-9]+)?)")
    set(${RESULT_LIST_VAR} "${PKG_NAME}=${CMAKE_MATCH_1}" PARENT_SCOPE)
  else()
    set(${RESULT_LIST_VAR} "${PKG_NAME}${REQ_STR}" PARENT_SCOPE)
  endif()
endfunction()

function(_catalog_resolve_version_conflict PACKAGE_NAME OUT_VER_VAR OUT_REQ_VAR)
  get_property(REQS GLOBAL PROPERTY "_CATALOG_${PACKAGE_NAME}_VERSION_REQS")

  if(NOT REQS)
    set(${OUT_VER_VAR} "" PARENT_SCOPE)
    set(${OUT_REQ_VAR} "" PARENT_SCOPE)
    return()
  endif()

  _catalog_get_var("VERSION_STRATEGY" STRATEGY)
  if(STRATEGY STREQUAL "")
    _catalog_get_var("${PACKAGE_NAME}_VERSION_STRATEGY" STRATEGY)
  endif()
  if(STRATEGY STREQUAL "")
    set(STRATEGY "NEWER")
  endif()

  string(TOUPPER "${STRATEGY}" STRATEGY)

  set(EXACT_VERSIONS "")
  set(MIN_VERSIONS "")
  set(MAX_VERSIONS "")
  set(HAS_UNCAPPED FALSE)
  set(HAS_CAPPED FALSE)

  foreach(REQ ${REQS})
    string(STRIP "${REQ}" REQ)
    if(REQ MATCHES "^(=|==)\\s*v?([0-9]+(\\.[0-9]+)*([-._]?[a-zA-Z0-9]+)?)$")
      list(APPEND EXACT_VERSIONS "${CMAKE_MATCH_2}")
    elseif(REQ MATCHES "^v?([^\\.\\s]+(\\.[^\\.\\s]+)*)\\s*(\\.\\.|-)\\s*v?([^\\.\\s]+(\\.[^\\.\\s]+)*)$")
      list(APPEND MIN_VERSIONS "${CMAKE_MATCH_1}")
      list(APPEND MAX_VERSIONS "${CMAKE_MATCH_4}")
      set(HAS_CAPPED TRUE)
    elseif(REQ MATCHES "^\\^v?([0-9]+\\.[0-9]+(\\.[0-9]+)?(.*))")
      set(RAW_V "${CMAKE_MATCH_1}")
      list(APPEND MIN_VERSIONS "${RAW_V}")
      if(RAW_V MATCHES "^([0-9]+)")
        math(EXPR NEXT_M "${CMAKE_MATCH_1} + 1")
        list(APPEND MAX_VERSIONS "${NEXT_M}.0.0")
      endif()
      set(HAS_CAPPED TRUE)
    elseif(REQ MATCHES "^~v?([0-9]+\\.[0-9]+(\\.[0-9]+)?(.*))")
      set(RAW_V "${CMAKE_MATCH_1}")
      list(APPEND MIN_VERSIONS "${RAW_V}")
      if(RAW_V MATCHES "^([0-9]+)\\.([0-9]+)")
        math(EXPR NEXT_M "${CMAKE_MATCH_2} + 1")
        list(APPEND MAX_VERSIONS "${CMAKE_MATCH_1}.${NEXT_M}.0")
      endif()
      set(HAS_CAPPED TRUE)
    elseif(REQ MATCHES "^(>=|>)\\s*v?([0-9]+(\\.[0-9]+)*([-._]?[a-zA-Z0-9]+)?)")
      list(APPEND MIN_VERSIONS "${CMAKE_MATCH_2}")
      set(HAS_UNCAPPED TRUE)
    elseif(REQ MATCHES "^(<=|<)\\s*v?([0-9]+(\\.[0-9]+)*([-._]?[a-zA-Z0-9]+)?)")
      list(APPEND MAX_VERSIONS "${CMAKE_MATCH_2}")
      set(HAS_CAPPED TRUE)
    elseif(REQ MATCHES "^v?([0-9]+(\\.[0-9]+)*([-._]?[a-zA-Z0-9]+)?)")
      list(APPEND EXACT_VERSIONS "${CMAKE_MATCH_1}")
    endif()
  endforeach()

  if(EXACT_VERSIONS)
    _catalog_sort_versions(EXACT_VERSIONS)
    list(GET EXACT_VERSIONS -1 CANDIDATE_EXACT)
    set(EXACT_VALID TRUE)

    foreach(REQ ${REQS})
      _catalog_version_satisfies("${CANDIDATE_EXACT}" "${REQ}" SAT)
      if(NOT SAT)
        set(EXACT_VALID FALSE)
        break()
      endif()
    endforeach()

    if(EXACT_VALID)
      set(${OUT_VER_VAR} "${CANDIDATE_EXACT}" PARENT_SCOPE)
      set(${OUT_REQ_VAR} "=${CANDIDATE_EXACT}" PARENT_SCOPE)
      return()
    endif()

    if(STRATEGY STREQUAL "STRICT" OR STRATEGY STREQUAL "EXACT")
      _catalog_log(FATAL_ERROR "Version conflict for ${PACKAGE_NAME}: requested exact version '${CANDIDATE_EXACT}' does not satisfy all requirements '${REQS}'.")
    endif()
  endif()

  if(MIN_VERSIONS)
    _catalog_sort_versions(MIN_VERSIONS)
    list(GET MIN_VERSIONS -1 HIGHEST_MIN)
  else()
    set(HIGHEST_MIN "")
  endif()

  if(MAX_VERSIONS)
    _catalog_sort_versions(MAX_VERSIONS)
    list(GET MAX_VERSIONS 0 LOWEST_MAX)
  else()
    set(LOWEST_MAX "")
  endif()

  if(HAS_CAPPED AND LOWEST_MAX)
    set(SELECTED_VER "${LOWEST_MAX}")
    set(SELECTED_REQ "<=${LOWEST_MAX}")
  elseif(HIGHEST_MIN)
    set(SELECTED_VER "${HIGHEST_MIN}")
    set(SELECTED_REQ ">=${HIGHEST_MIN}")
  else()
    list(GET REQS 0 FIRST_REQ)
    set(SELECTED_VER "")
    set(SELECTED_REQ "${FIRST_REQ}")
  endif()

  if(STRATEGY STREQUAL "STRICT" OR STRATEGY STREQUAL "EXACT")
    if(SELECTED_VER)
      foreach(REQ ${REQS})
        _catalog_version_satisfies("${SELECTED_VER}" "${REQ}" SAT)
        if(NOT SAT)
          _catalog_log(FATAL_ERROR "Version conflict for ${PACKAGE_NAME}: selected version '${SELECTED_VER}' does not satisfy requirement '${REQ}'.")
        endif()
      endforeach()
    endif()
  endif()

  set(${OUT_VER_VAR} "${SELECTED_VER}" PARENT_SCOPE)
  set(${OUT_REQ_VAR} "${SELECTED_REQ}" PARENT_SCOPE)
endfunction()

macro(_catalog_log_verbose MESSAGE)
  _catalog_is_var_defined("VERBOSE" _LOG_VERBOSE ENV)
  if(_LOG_VERBOSE)
    message(STATUS "[Catalog] ${MESSAGE}")
  endif()
endmacro()

function(_catalog_download_file URL PATH)
  _catalog_log_verbose(STATUS "Downloading ${URL}")
  set(TMP_PATH "${PATH}.tmp")

  _catalog_get_var("DOWNLOAD_PROVIDER" DOWNLOAD_PROVIDER ENV)
  if(NOT "${DOWNLOAD_PROVIDER}" STREQUAL "")
    string(TOLOWER "${DOWNLOAD_PROVIDER}" DOWNLOAD_PROVIDER)
    if(NOT DOWNLOAD_PROVIDER MATCHES "^(curl|wget|cmake)$")
      _catalog_log(FATAL_ERROR "Invalid DOWNLOAD_PROVIDER '${DOWNLOAD_PROVIDER}' (expected curl, wget, or cmake)")
    endif()
  endif()

  if(NOT DOWNLOAD_PROVIDER STREQUAL "cmake")
    find_program(_CATALOG_CURL_EXECUTABLE curl)
    find_program(_CATALOG_WGET_EXECUTABLE wget)
  endif()

  set(DL_DONE FALSE)
  if(NOT DOWNLOAD_PROVIDER STREQUAL "wget" AND NOT DOWNLOAD_PROVIDER STREQUAL "cmake" AND _CATALOG_CURL_EXECUTABLE)
    execute_process(
      COMMAND "${_CATALOG_CURL_EXECUTABLE}" --fail --location --progress-bar
              --connect-timeout 20 --max-time 300 --speed-time 20 --speed-limit 1
              -o "${TMP_PATH}" "${URL}"
      RESULT_VARIABLE DL_RES
    )
    if(DL_RES EQUAL 0)
      set(DL_DONE TRUE)
    else()
      file(REMOVE "${TMP_PATH}")
      if(DOWNLOAD_PROVIDER STREQUAL "curl")
        _catalog_log(FATAL_ERROR "Download failed via curl: ${URL}")
      endif()
    endif()
  elseif(NOT DOWNLOAD_PROVIDER STREQUAL "curl" AND NOT DOWNLOAD_PROVIDER STREQUAL "cmake" AND _CATALOG_WGET_EXECUTABLE)
    execute_process(
      COMMAND "${_CATALOG_WGET_EXECUTABLE}" --progress=bar:force:noscroll
              --tries=1 --timeout=20 -O "${TMP_PATH}" "${URL}"
      RESULT_VARIABLE DL_RES
    )
    if(DL_RES EQUAL 0)
      set(DL_DONE TRUE)
    else()
      file(REMOVE "${TMP_PATH}")
      if(DOWNLOAD_PROVIDER STREQUAL "wget")
        _catalog_log(FATAL_ERROR "Download failed via wget: ${URL}")
      endif()
    endif()
  elseif(DOWNLOAD_PROVIDER STREQUAL "curl")
    _catalog_log(FATAL_ERROR "DOWNLOAD_PROVIDER is 'curl' but the curl executable was not found")
  elseif(DOWNLOAD_PROVIDER STREQUAL "wget")
    _catalog_log(FATAL_ERROR "DOWNLOAD_PROVIDER is 'wget' but the wget executable was not found")
  endif()

  if(NOT DL_DONE)
    file(DOWNLOAD ${URL} ${TMP_PATH} SHOW_PROGRESS TIMEOUT 300 INACTIVITY_TIMEOUT 20 STATUS DL_STATUS)
    list(GET DL_STATUS 0 RES)
    if(NOT RES EQUAL 0)
      list(GET DL_STATUS 1 ERR_MSG)
      file(REMOVE ${TMP_PATH})
      _catalog_log(FATAL_ERROR "Download failed: ${ERR_MSG}")
    endif()
  endif()

  file(RENAME ${TMP_PATH} ${PATH})
endfunction()

function(_catalog_download_file_with_checksum URL PATH EXPECTED_SHA256)
  _catalog_download_file(${URL} ${PATH})
  
  file(SHA256 ${PATH} FILE_SHA256)
  if(NOT FILE_SHA256 STREQUAL EXPECTED_SHA256)
    file(REMOVE ${PATH})
    _catalog_log(FATAL_ERROR "Checksum mismatch for ${PATH}. Expected ${EXPECTED_SHA256}, got ${FILE_SHA256}")
  endif()
endfunction()

function(_catalog_extract_archive ARCHIVE_PATH EXTRACT_DIR)
  if(NOT EXISTS ${ARCHIVE_PATH})
    _catalog_log(FATAL_ERROR "Archive not found: ${ARCHIVE_PATH}")
  endif()
  
  file(MAKE_DIRECTORY ${EXTRACT_DIR})
  
  file(ARCHIVE_EXTRACT INPUT ${ARCHIVE_PATH} DESTINATION ${EXTRACT_DIR})
  _catalog_log_verbose("Extracted ${ARCHIVE_PATH} to ${EXTRACT_DIR}")
endfunction()

block(PROPAGATE CATALOG_SYSTEM_ARCH CATALOG_SYSTEM_ID)
  if(CMAKE_SYSTEM_PROCESSOR MATCHES "x86_64|AMD64|amd64")
    set(CATALOG_SYSTEM_ARCH "x86_64")
  elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "i[3-6]86|x86")
    set(CATALOG_SYSTEM_ARCH "x86")
  elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "aarch64|arm64|ARM64")
    set(CATALOG_SYSTEM_ARCH "aarch64")
  elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "armv7|armv7l|armv7-a")
    set(CATALOG_SYSTEM_ARCH "armv7")
  elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "armv6|armv6l")
    set(CATALOG_SYSTEM_ARCH "armv6")
  elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "ppc64|powerpc64|ppc64le")
    set(CATALOG_SYSTEM_ARCH "ppc64")
  elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "s390x")
    set(CATALOG_SYSTEM_ARCH "s390x")
  elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "riscv64")
    set(CATALOG_SYSTEM_ARCH "riscv64")
  else()
    set(CATALOG_SYSTEM_ARCH "${CMAKE_SYSTEM_PROCESSOR}")
  endif()

  if(APPLE)
    if(CMAKE_SYSTEM_PROCESSOR MATCHES "arm64|aarch64")
      set(CATALOG_SYSTEM_ID "macos-arm64")
    else()
      set(CATALOG_SYSTEM_ID "macos-x86_64")
    endif()
  elseif(MSVC OR WIN32)
    set(CATALOG_SYSTEM_ID "windows-x86_64")
  elseif(CMAKE_HOST_SYSTEM_NAME STREQUAL "Linux")
    set(CATALOG_SYSTEM_ID "linux-${CATALOG_SYSTEM_ARCH}")
  else()
    set(CATALOG_SYSTEM_ID "${CMAKE_HOST_SYSTEM_NAME}-${CATALOG_SYSTEM_ARCH}")
  endif()
endblock()

function(_catalog_detect_system_arch RESULT_VAR)
  set(${RESULT_VAR} "${CATALOG_SYSTEM_ARCH}" PARENT_SCOPE)
endfunction()

function(_catalog_get_system_identifier RESULT_VAR)
  set(${RESULT_VAR} "${CATALOG_SYSTEM_ID}" PARENT_SCOPE)
endfunction()

block(PROPAGATE CATALOG_PACKAGE_MANAGER CATALOG_PACKAGE_REPO)
  if(DEFINED DEVKITPRO)
    find_program(DKP_PACMAN "dkp-pacman")
    if(DKP_PACMAN)
      set(CATALOG_PACKAGE_MANAGER "dkp-pacman")
      set(CATALOG_PACKAGE_REPO "devkitpro")
    else()
      set(CATALOG_PACKAGE_MANAGER "pacman")
      set(CATALOG_PACKAGE_REPO "devkitpro")
    endif()
  elseif(APPLE)
    find_program(BREW "brew")
    find_program(PORT "port")

    if(BREW)
      set(CATALOG_PACKAGE_MANAGER "brew")
      set(CATALOG_PACKAGE_REPO "homebrew")
    elseif(PORT)
      set(CATALOG_PACKAGE_MANAGER "port")
      set(CATALOG_PACKAGE_REPO "macports")
    endif()
  elseif(CMAKE_HOST_SYSTEM_NAME STREQUAL "Linux" AND EXISTS "/etc/os-release")
    file(STRINGS "/etc/os-release" os_release_lines REGEX "^(ID|ID_LIKE|VERSION_ID)=")
    
    set(LINUX_IDS "")
    foreach(line ${os_release_lines})
      string(REGEX REPLACE "^[A-Z_]+=" "" val "${line}")
      string(REPLACE "\"" "" val "${val}")
      
      if(line MATCHES "^ID=")
        list(APPEND LINUX_IDS "${val}")
      elseif(line MATCHES "^ID_LIKE=")
        separate_arguments(like_list UNIX_COMMAND "${val}")
        list(APPEND LINUX_IDS ${like_list})
      endif()
    endforeach()

    foreach(id ${LINUX_IDS})
      if(id MATCHES "^(debian|ubuntu|pop|mint|kali|raspbian|devuan|zorin|deepin)$")
        set(CATALOG_PACKAGE_MANAGER "apt")
      elseif(id MATCHES "^(rhel|centos|fedora|almalinux|rocky|ol|amzn|xcp-ng)$")
        set(CATALOG_PACKAGE_MANAGER "yum")
      elseif(id MATCHES "^(arch|manjaro|endeavouros|artix)$")
        set(CATALOG_PACKAGE_MANAGER "pacman")
      elseif(id MATCHES "^(alpine)$")
        set(CATALOG_PACKAGE_MANAGER "apk")
      elseif(id MATCHES "^(suse|opensuse|sles)$")
        set(CATALOG_PACKAGE_MANAGER "zypper")
      elseif(id MATCHES "^(gentoo)$")
        set(CATALOG_PACKAGE_MANAGER "emerge")
      endif()

      if(id MATCHES "^(debian|devuan|kali|raspbian)$")
        set(CATALOG_PACKAGE_REPO "debian")
      elseif(id MATCHES "^(ubuntu|pop|mint|zorin)$")
        set(CATALOG_PACKAGE_REPO "ubuntu")
      elseif(id MATCHES "^(rhel|centos|almalinux|rocky|ol)$")
        set(CATALOG_PACKAGE_REPO "rhel")
      elseif(id MATCHES "^(fedora|amzn)$")
        set(CATALOG_PACKAGE_REPO "fedora")
      elseif(id MATCHES "^(arch|manjaro|endeavouros|artix)$")
        set(CATALOG_PACKAGE_REPO "arch")
      else()
        set(CATALOG_PACKAGE_REPO "${id}")
      endif()
      
      if(DEFINED CATALOG_PACKAGE_MANAGER)
        break()
      endif()
    endforeach()
  endif()
endblock()

function(_catalog_resolve_recipe_url SOURCE_STR RESULT_VAR)
  set(IS_LOCAL FALSE)
  if(EXISTS "${SOURCE_STR}" AND NOT IS_DIRECTORY "${SOURCE_STR}")
    set(IS_LOCAL TRUE)
  elseif(SOURCE_STR MATCHES "^\\./" OR SOURCE_STR MATCHES "^\\.\\./" OR SOURCE_STR MATCHES "^/")
    set(IS_LOCAL TRUE)
  endif()

  if(IS_LOCAL)
    get_filename_component(ABS_PATH "${SOURCE_STR}" ABSOLUTE)
    set(RESOLVED "${ABS_PATH}")
  elseif(SOURCE_STR MATCHES "^https?://(www\\.)?github\\.com/([^/]+)/([^/]+)(/(tree|blob)/([^/]+)(/(.*))?)?/?$")
    set(GH_USER "${CMAKE_MATCH_2}")
    set(GH_REPO "${CMAKE_MATCH_3}")
    set(GH_REF  "${CMAKE_MATCH_6}")
    set(GH_FILE "${CMAKE_MATCH_8}")
    
    string(REGEX REPLACE "\\.git$" "" GH_REPO "${GH_REPO}")
    
    if(GH_FILE STREQUAL "")
      set(GH_FILE "recipe.cmake")
    endif()
    
    if(GH_REF STREQUAL "")
      set(RESOLVED "https://raw.githubusercontent.com/${GH_USER}/${GH_REPO}/HEAD/${GH_FILE}")
    else()
      set(RESOLVED "https://raw.githubusercontent.com/${GH_USER}/${GH_REPO}/${GH_REF}/${GH_FILE}")
    endif()
  elseif(SOURCE_STR MATCHES "^https?://")
    set(RESOLVED "${SOURCE_STR}")
  else()
    if(SOURCE_STR MATCHES "^([^/]+)/([^/@#]+)(/([^@#]+))?([@#](.*))?$")
      set(GH_USER "${CMAKE_MATCH_1}")
      set(GH_REPO "${CMAKE_MATCH_2}")
      set(GH_FILE "${CMAKE_MATCH_4}")
      set(GH_REF  "${CMAKE_MATCH_6}")
      
      if(GH_FILE STREQUAL "")
        set(GH_FILE "recipe.cmake")
      endif()
      
      if(GH_REF STREQUAL "")
        set(RESOLVED "https://raw.githubusercontent.com/${GH_USER}/${GH_REPO}/HEAD/${GH_FILE}")
      else()
        set(RESOLVED "https://raw.githubusercontent.com/${GH_USER}/${GH_REPO}/${GH_REF}/${GH_FILE}")
      endif()
    else()
      message(FATAL_ERROR "[Catalog] Invalid recipe source: ${SOURCE_STR}")
    endif()
  endif()
  
  set(${RESULT_VAR} "${RESOLVED}" PARENT_SCOPE)
endfunction()

function(_catalog_clone_recipe_repo GIT_URL REF RESULT_DIR_VAR)
  _catalog_get_cache_dir(CACHE_DIR)

  string(SHA256 CLONE_HASH "${GIT_URL}@${REF}")
  string(SUBSTRING "${CLONE_HASH}" 0 12 CLONE_HASH_SHORT)
  set(CHECKOUT_DIR "${CACHE_DIR}/recipe_src_${CLONE_HASH_SHORT}")

  if(NOT EXISTS "${CHECKOUT_DIR}/.git")
    file(REMOVE_RECURSE "${CHECKOUT_DIR}")
    _catalog_log(STATUS "Cloning ${GIT_URL} for recipe...")
    execute_process(
      COMMAND git clone --quiet ${GIT_URL} ${CHECKOUT_DIR}
      RESULT_VARIABLE GIT_RESULT
      ERROR_VARIABLE GIT_ERROR
    )
    if(NOT GIT_RESULT EQUAL 0)
      _catalog_log(FATAL_ERROR "Failed to clone repository ${GIT_URL}: ${GIT_ERROR}")
    endif()

    if(NOT REF STREQUAL "" AND NOT REF STREQUAL "HEAD")
      execute_process(
        COMMAND git checkout --quiet ${REF}
        WORKING_DIRECTORY ${CHECKOUT_DIR}
        RESULT_VARIABLE CHECKOUT_RESULT
        ERROR_VARIABLE CHECKOUT_ERROR
      )
      if(NOT CHECKOUT_RESULT EQUAL 0)
        _catalog_log(FATAL_ERROR "Failed to checkout ref ${REF} in ${GIT_URL}: ${CHECKOUT_ERROR}")
      endif()
    endif()
  endif()

  set(${RESULT_DIR_VAR} "${CHECKOUT_DIR}" PARENT_SCOPE)
endfunction()

function(_catalog_resolve_dep_shorthand SOURCE_STR PACKAGE_NAME_VAR RECIPE_SPEC_VAR IS_SHORTHAND_VAR)
  set(${IS_SHORTHAND_VAR} FALSE PARENT_SCOPE)

  if(SOURCE_STR MATCHES "^gh:(.+)$")
    set(RECIPE_SPEC "${CMAKE_MATCH_1}")

    if(NOT RECIPE_SPEC MATCHES "^[^/]+/([^/@#]+)")
      _catalog_log(FATAL_ERROR "Invalid gh: dependency shorthand '${SOURCE_STR}' (expected gh:<owner>/<repo>[@ref])")
    endif()

    set(REPO_NAME "${CMAKE_MATCH_1}")
    string(REGEX REPLACE "\\.git$" "" REPO_NAME "${REPO_NAME}")

    _catalog_valid_target_name("${REPO_NAME}" VALID_NAME)
    if(NOT VALID_NAME)
      _catalog_log(FATAL_ERROR "Repository name '${REPO_NAME}' inferred from '${SOURCE_STR}' is not a valid package name; register it with catalog_add_recipe(<name> ${RECIPE_SPEC}) instead")
    endif()

    set(${PACKAGE_NAME_VAR} "${REPO_NAME}" PARENT_SCOPE)
    set(${RECIPE_SPEC_VAR} "${RECIPE_SPEC}" PARENT_SCOPE)
    set(${IS_SHORTHAND_VAR} TRUE PARENT_SCOPE)
    return()
  endif()

  if(SOURCE_STR MATCHES "^(https?)://([^/]+)/([^/]+)/([^/@]+)(@(.+))?/?$")
    set(SCHEME "${CMAKE_MATCH_1}")
    set(HOST "${CMAKE_MATCH_2}")
    set(GH_USER "${CMAKE_MATCH_3}")
    set(REPO_RAW "${CMAKE_MATCH_4}")
    set(REF "${CMAKE_MATCH_6}")
    if(REF STREQUAL "")
      set(REF "HEAD")
    endif()
    string(REGEX REPLACE "\\.git$" "" REPO_NAME "${REPO_RAW}")
    set(GIT_URL "${SCHEME}://${HOST}/${GH_USER}/${REPO_NAME}.git")
  elseif(SOURCE_STR MATCHES "^git@([^:]+):([^/]+)/([^/]+)$")
    set(REPO_RAW "${CMAKE_MATCH_3}")
    string(REGEX REPLACE "\\.git$" "" REPO_NAME "${REPO_RAW}")
    set(REF "HEAD")
    set(GIT_URL "${SOURCE_STR}")
  else()
    return()
  endif()

  _catalog_valid_target_name("${REPO_NAME}" VALID_NAME)
  if(NOT VALID_NAME)
    _catalog_log(FATAL_ERROR "Repository name '${REPO_NAME}' inferred from '${SOURCE_STR}' is not a valid package name; register it with catalog_add_recipe() instead")
  endif()

  _catalog_clone_recipe_repo("${GIT_URL}" "${REF}" CHECKOUT_DIR)

  set(${PACKAGE_NAME_VAR} "${REPO_NAME}" PARENT_SCOPE)
  set(${RECIPE_SPEC_VAR} "${CHECKOUT_DIR}/recipe.cmake" PARENT_SCOPE)
  set(${IS_SHORTHAND_VAR} TRUE PARENT_SCOPE)
endfunction()

function(_catalog_resolve_repo_url SOURCE_STR RESULT_VAR TYPE_VAR BASE_VAR NAME_VAR)
  set(IS_LOCAL FALSE)
  if(EXISTS "${SOURCE_STR}" AND IS_DIRECTORY "${SOURCE_STR}")
    set(IS_LOCAL TRUE)
  elseif(SOURCE_STR MATCHES "^\\./" OR SOURCE_STR MATCHES "^\\.\\./" OR SOURCE_STR MATCHES "^/")
    set(IS_LOCAL TRUE)
  endif()
  
  if(IS_LOCAL)
    get_filename_component(ABS_DIR "${SOURCE_STR}" ABSOLUTE)
    set(${RESULT_VAR} "${ABS_DIR}/meta.cmake" PARENT_SCOPE)
    set(${TYPE_VAR} "local" PARENT_SCOPE)
    set(${BASE_VAR} "${ABS_DIR}" PARENT_SCOPE)
    get_filename_component(DIR_NAME "${ABS_DIR}" NAME)
    set(${NAME_VAR} "${DIR_NAME}" PARENT_SCOPE)
  elseif(SOURCE_STR MATCHES "^https?://")
    if(SOURCE_STR MATCHES "\\.cmake$")
      set(RESOLVED "${SOURCE_STR}")
      string(REGEX REPLACE "/[^/]+\\.cmake$" "" BASE "${SOURCE_STR}")
    else()
      string(REGEX REPLACE "/$" "" STR_CLEAN "${SOURCE_STR}")
      set(RESOLVED "${STR_CLEAN}/meta.cmake")
      set(BASE "${STR_CLEAN}")
    endif()
    set(${RESULT_VAR} "${RESOLVED}" PARENT_SCOPE)
    set(${TYPE_VAR} "url" PARENT_SCOPE)
    set(${BASE_VAR} "${BASE}" PARENT_SCOPE)
    string(REGEX MATCH "[^/]+$" URL_NAME "${BASE}")
    set(${NAME_VAR} "${URL_NAME}" PARENT_SCOPE)
  else()
    if(SOURCE_STR MATCHES "^([^/]+)/([^@#]+)([@#](.+))?$")
      set(GH_USER "${CMAKE_MATCH_1}")
      set(GH_REPO "${CMAKE_MATCH_2}")
      set(GH_REF "${CMAKE_MATCH_4}")
      if(GH_REF STREQUAL "")
        set(GH_REF "HEAD")
      endif()
      
      set(RESOLVED "https://raw.githubusercontent.com/${GH_USER}/${GH_REPO}/${GH_REF}/meta.cmake")
      set(BASE "https://raw.githubusercontent.com/${GH_USER}/${GH_REPO}/${GH_REF}")
      
      set(${RESULT_VAR} "${RESOLVED}" PARENT_SCOPE)
      set(${TYPE_VAR} "github" PARENT_SCOPE)
      set(${BASE_VAR} "${BASE}" PARENT_SCOPE)
      set(${NAME_VAR} "${GH_USER}_${GH_REPO}" PARENT_SCOPE)
    else()
      _catalog_log(FATAL_ERROR "Invalid repository source: ${SOURCE_STR}")
    endif()
  endif()
endfunction()

function(_catalog_find_pkgconfig_package PACKAGE_NAME RESULT_VAR)
  find_package(PkgConfig QUIET)
  if(PkgConfig_FOUND)
    pkg_check_modules(PKG_CONFIG_${PACKAGE_NAME} QUIET ${PACKAGE_NAME})
    if(PKG_CONFIG_${PACKAGE_NAME}_FOUND)
      set(${RESULT_VAR} TRUE PARENT_SCOPE)
    else()
      set(${RESULT_VAR} FALSE PARENT_SCOPE)
    endif()
  else()
    set(${RESULT_VAR} FALSE PARENT_SCOPE)
  endif()
endfunction()

function(_catalog_get_cache_dir RESULT_VAR)
  _catalog_get_var("CACHE_DIR" CACHE_DIR_VAL ENV)
  _catalog_is_var_defined("LOCAL_CACHE" HAS_LOCAL_CACHE ENV)

  if(NOT "${CACHE_DIR_VAL}" STREQUAL "")
    set(CACHE_DIR "${CACHE_DIR_VAL}")
  elseif(CMAKE_CROSSCOMPILING OR HAS_LOCAL_CACHE)
    set(CACHE_DIR "${CMAKE_CURRENT_BINARY_DIR}/.cache/catalog")
  else()
    if(WIN32)
      set(CACHE_DIR "$ENV{LOCALAPPDATA}/catalog")
    else()
      set(CACHE_DIR "$ENV{HOME}/.cache/catalog")
    endif()
  endif()
  
  file(MAKE_DIRECTORY "${CACHE_DIR}")
  set(${RESULT_VAR} "${CACHE_DIR}" PARENT_SCOPE)
endfunction()

function(_catalog_load_recipe RECIPE_URL RECIPE_OUTPUT_VAR)
  if(NOT RECIPE_URL)
    _catalog_log(FATAL_ERROR "Recipe URL cannot be empty")
  endif()

  if(EXISTS "${RECIPE_URL}")
    set(${RECIPE_OUTPUT_VAR} "${RECIPE_URL}" PARENT_SCOPE)
    return()
  endif()

  _catalog_get_cache_dir(CACHE_DIR)

  string(SHA256 RECIPE_HASH "${RECIPE_URL}")
  string(SUBSTRING "${RECIPE_HASH}" 0 12 RECIPE_HASH_SHORT)
  set(RECIPE_FILE "${CACHE_DIR}/recipe_${RECIPE_HASH_SHORT}.cmake")

  set(FORCE_REFRESH FALSE)
  if(ARGC GREATER 2)
    set(FORCE_REFRESH "${ARGV2}")
  endif()

  if(FORCE_REFRESH AND EXISTS ${RECIPE_FILE})
    file(REMOVE ${RECIPE_FILE})
  endif()

  if(NOT EXISTS ${RECIPE_FILE})
    _catalog_download_file(${RECIPE_URL} ${RECIPE_FILE})
  endif()

  set(${RECIPE_OUTPUT_VAR} "${RECIPE_FILE}" PARENT_SCOPE)
endfunction()

function(_catalog_load_repo_file FILE_URL RESULT_VAR)
  if(NOT FILE_URL)
    _catalog_log(FATAL_ERROR "Repo file URL cannot be empty")
  endif()

  if(EXISTS "${FILE_URL}")
    set(${RESULT_VAR} "${FILE_URL}" PARENT_SCOPE)
    return()
  endif()

  _catalog_get_cache_dir(CACHE_DIR)

  get_filename_component(FILE_EXT "${FILE_URL}" LAST_EXT)
  string(SHA256 FILE_HASH "${FILE_URL}")
  string(SUBSTRING "${FILE_HASH}" 0 12 FILE_HASH_SHORT)
  set(CACHED_FILE "${CACHE_DIR}/repofile_${FILE_HASH_SHORT}${FILE_EXT}")

  if(NOT EXISTS "${CACHED_FILE}")
    _catalog_download_file("${FILE_URL}" "${CACHED_FILE}")
  endif()

  set(${RESULT_VAR} "${CACHED_FILE}" PARENT_SCOPE)
endfunction()

function(_catalog_valid_target_name NAME RESULT_VAR)
  if(NAME MATCHES "^[a-zA-Z0-9_:-]+$")
    set(${RESULT_VAR} TRUE PARENT_SCOPE)
  else()
    set(${RESULT_VAR} FALSE PARENT_SCOPE)
  endif()
endfunction()
