macro(_catalog_log LEVEL MESSAGE)
  message(${LEVEL} "[Catalog] ${MESSAGE}")
endmacro()

macro(_catalog_get_var_prefixes RESULT_LIST_VAR)
  set(${RESULT_LIST_VAR} "CATALOG_" "CL_")
  if(DEFINED CATALOG_PREFIX AND NOT CATALOG_PREFIX STREQUAL "")
    string(TOUPPER "${CATALOG_PREFIX}" _UP_PREF)
    if(NOT _UP_PREF MATCHES "_$")
      string(APPEND _UP_PREF "_")
    endif()
    list(FIND ${RESULT_LIST_VAR} "${_UP_PREF}" _PREF_IDX)
    if(_PREF_IDX EQUAL -1)
      list(APPEND ${RESULT_LIST_VAR} "${_UP_PREF}")
    endif()
  endif()
endmacro()

function(_catalog_is_var_defined SUFFIX RESULT_VAR)
  set(options ENV)
  cmake_parse_arguments(IS_DEF "${options}" "" "" ${ARGN})

  _catalog_get_var_prefixes(_PREFIXES)
  foreach(_P ${_PREFIXES})
    if(DEFINED "${_P}${SUFFIX}")
      set(${RESULT_VAR} TRUE PARENT_SCOPE)
      return()
    endif()
  endforeach()

  if(IS_DEF_ENV)
    foreach(_P ${_PREFIXES})
      string(REGEX REPLACE "_$" "" _ENV_P "${_P}")
      if(DEFINED ENV{${_ENV_P}_${SUFFIX}})
        set(${RESULT_VAR} TRUE PARENT_SCOPE)
        return()
      endif()
    endforeach()
  endif()

  set(${RESULT_VAR} FALSE PARENT_SCOPE)
endfunction()

function(_catalog_get_var SUFFIX RESULT_VAR)
  set(options ENV)
  cmake_parse_arguments(GET_VAR "${options}" "" "" ${ARGN})

  _catalog_get_var_prefixes(_PREFIXES)
  foreach(_P ${_PREFIXES})
    if(DEFINED "${_P}${SUFFIX}")
      set(${RESULT_VAR} "${${_P}${SUFFIX}}" PARENT_SCOPE)
      return()
    endif()
  endforeach()

  if(GET_VAR_ENV)
    foreach(_P ${_PREFIXES})
      string(REGEX REPLACE "_$" "" _ENV_P "${_P}")
      if(DEFINED ENV{${_ENV_P}_${SUFFIX}})
        set(${RESULT_VAR} "$ENV{${_ENV_P}_${SUFFIX}}" PARENT_SCOPE)
        return()
      endif()
    endforeach()
  endif()

  set(${RESULT_VAR} "" PARENT_SCOPE)
endfunction()

macro(_catalog_set_var SUFFIX VALUE)
  _catalog_get_var_prefixes(_PREFIXES)
  foreach(_P ${_PREFIXES})
    set("${_P}${SUFFIX}" "${VALUE}")
    set("${_P}${SUFFIX}" "${VALUE}" PARENT_SCOPE)
  endforeach()
endmacro()

macro(_catalog_log_verbose MESSAGE)
  _catalog_is_var_defined("VERBOSE" _LOG_VERBOSE ENV)
  if(_LOG_VERBOSE)
    message(STATUS "[Catalog] ${MESSAGE}")
  endif()
endmacro()

function(_catalog_download_file URL PATH)
  _catalog_log_verbose(STATUS "Downloading ${URL}")
  set(TMP_PATH "${PATH}.tmp")
  file(DOWNLOAD ${URL} ${TMP_PATH} SHOW_PROGRESS TIMEOUT 300 INACTIVITY_TIMEOUT 20 STATUS DL_STATUS)
  list(GET DL_STATUS 0 RES)
  if(NOT RES EQUAL 0)
    list(GET DL_STATUS 1 ERR_MSG)
    file(REMOVE ${TMP_PATH})
    _catalog_log(FATAL_ERROR "Download failed: ${ERR_MSG}")
  endif()
  file(RENAME ${TMP_PATH} ${PATH})
endfunction()

function(_catalog_download_file_with_checksum URL PATH EXPECTED_SHA256)
  _catalog_download_file(${URL} ${PATH})
  
  file(SHA256 ${PATH} FILE_SHA256)
  if(NOT FILE_SHA256 STREQUAL EXPECTED_SHA256)
    file(REMOVE ${PATH})
    _catalog_log(FATAL_ERROR "Checksum mismatch for ${PATH}. Expected ${EXPECTED_SHA256}, got ${FILE_SHA256}")
  endif()
endfunction()

function(_catalog_extract_archive ARCHIVE_PATH EXTRACT_DIR)
  if(NOT EXISTS ${ARCHIVE_PATH})
    _catalog_log(FATAL_ERROR "Archive not found: ${ARCHIVE_PATH}")
  endif()
  
  file(MAKE_DIRECTORY ${EXTRACT_DIR})
  
  file(ARCHIVE_EXTRACT INPUT ${ARCHIVE_PATH} DESTINATION ${EXTRACT_DIR})
  _catalog_log_verbose("Extracted ${ARCHIVE_PATH} to ${EXTRACT_DIR}")
endfunction()

block(PROPAGATE CATALOG_SYSTEM_ARCH CATALOG_SYSTEM_ID)
  if(CMAKE_SYSTEM_PROCESSOR MATCHES "x86_64|AMD64|amd64")
    set(CATALOG_SYSTEM_ARCH "x86_64")
  elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "i[3-6]86|x86")
    set(CATALOG_SYSTEM_ARCH "x86")
  elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "aarch64|arm64|ARM64")
    set(CATALOG_SYSTEM_ARCH "aarch64")
  elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "armv7|armv7l|armv7-a")
    set(CATALOG_SYSTEM_ARCH "armv7")
  elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "armv6|armv6l")
    set(CATALOG_SYSTEM_ARCH "armv6")
  elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "ppc64|powerpc64|ppc64le")
    set(CATALOG_SYSTEM_ARCH "ppc64")
  elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "s390x")
    set(CATALOG_SYSTEM_ARCH "s390x")
  elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "riscv64")
    set(CATALOG_SYSTEM_ARCH "riscv64")
  else()
    set(CATALOG_SYSTEM_ARCH "${CMAKE_SYSTEM_PROCESSOR}")
  endif()

  if(APPLE)
    if(CMAKE_SYSTEM_PROCESSOR MATCHES "arm64|aarch64")
      set(CATALOG_SYSTEM_ID "macos-arm64")
    else()
      set(CATALOG_SYSTEM_ID "macos-x86_64")
    endif()
  elseif(MSVC OR WIN32)
    set(CATALOG_SYSTEM_ID "windows-x86_64")
  elseif(CMAKE_HOST_SYSTEM_NAME STREQUAL "Linux")
    set(CATALOG_SYSTEM_ID "linux-${CATALOG_SYSTEM_ARCH}")
  else()
    set(CATALOG_SYSTEM_ID "${CMAKE_HOST_SYSTEM_NAME}-${CATALOG_SYSTEM_ARCH}")
  endif()
endblock()

function(_catalog_detect_system_arch RESULT_VAR)
  set(${RESULT_VAR} "${CATALOG_SYSTEM_ARCH}" PARENT_SCOPE)
endfunction()

function(_catalog_get_system_identifier RESULT_VAR)
  set(${RESULT_VAR} "${CATALOG_SYSTEM_ID}" PARENT_SCOPE)
endfunction()

block(PROPAGATE CATALOG_PACKAGE_MANAGER CATALOG_PACKAGE_REPO)
  if(DEFINED DEVKITPRO)
    find_program(DKP_PACMAN "dkp-pacman")
    if(DKP_PACMAN)
      set(CATALOG_PACKAGE_MANAGER "dkp-pacman")
      set(CATALOG_PACKAGE_REPO "devkitpro")
    else()
      set(CATALOG_PACKAGE_MANAGER "pacman")
      set(CATALOG_PACKAGE_REPO "devkitpro")
    endif()
  elseif(APPLE)
    find_program(BREW "brew")
    find_program(PORT "port")

    if(BREW)
      set(CATALOG_PACKAGE_MANAGER "brew")
      set(CATALOG_PACKAGE_REPO "homebrew")
    elseif(PORT)
      set(CATALOG_PACKAGE_MANAGER "port")
      set(CATALOG_PACKAGE_REPO "macports")
    endif()
  elseif(CMAKE_HOST_SYSTEM_NAME STREQUAL "Linux" AND EXISTS "/etc/os-release")
    file(STRINGS "/etc/os-release" os_release_lines REGEX "^(ID|ID_LIKE|VERSION_ID)=")
    
    set(LINUX_IDS "")
    foreach(line ${os_release_lines})
      string(REGEX REPLACE "^[A-Z_]+=" "" val "${line}")
      string(REPLACE "\"" "" val "${val}")
      
      if(line MATCHES "^ID=")
        list(APPEND LINUX_IDS "${val}")
      elseif(line MATCHES "^ID_LIKE=")
        separate_arguments(like_list UNIX_COMMAND "${val}")
        list(APPEND LINUX_IDS ${like_list})
      endif()
    endforeach()

    foreach(id ${LINUX_IDS})
      if(id MATCHES "^(debian|ubuntu|pop|mint|kali|raspbian|devuan|zorin|deepin)$")
        set(CATALOG_PACKAGE_MANAGER "apt")
      elseif(id MATCHES "^(rhel|centos|fedora|almalinux|rocky|ol|amzn|xcp-ng)$")
        set(CATALOG_PACKAGE_MANAGER "yum")
      elseif(id MATCHES "^(arch|manjaro|endeavouros|artix)$")
        set(CATALOG_PACKAGE_MANAGER "pacman")
      elseif(id MATCHES "^(alpine)$")
        set(CATALOG_PACKAGE_MANAGER "apk")
      elseif(id MATCHES "^(suse|opensuse|sles)$")
        set(CATALOG_PACKAGE_MANAGER "zypper")
      elseif(id MATCHES "^(gentoo)$")
        set(CATALOG_PACKAGE_MANAGER "emerge")
      endif()

      if(id MATCHES "^(debian|devuan|kali|raspbian)$")
        set(CATALOG_PACKAGE_REPO "debian")
      elseif(id MATCHES "^(ubuntu|pop|mint|zorin)$")
        set(CATALOG_PACKAGE_REPO "ubuntu")
      elseif(id MATCHES "^(rhel|centos|almalinux|rocky|ol)$")
        set(CATALOG_PACKAGE_REPO "rhel")
      elseif(id MATCHES "^(fedora|amzn)$")
        set(CATALOG_PACKAGE_REPO "fedora")
      elseif(id MATCHES "^(arch|manjaro|endeavouros|artix)$")
        set(CATALOG_PACKAGE_REPO "arch")
      else()
        set(CATALOG_PACKAGE_REPO "${id}")
      endif()
      
      if(DEFINED CATALOG_PACKAGE_MANAGER)
        break()
      endif()
    endforeach()
  endif()
endblock()

function(_catalog_resolve_recipe_url SOURCE_STR RESULT_VAR)
  set(IS_LOCAL FALSE)
  if(EXISTS "${SOURCE_STR}" AND NOT IS_DIRECTORY "${SOURCE_STR}")
    set(IS_LOCAL TRUE)
  elseif(SOURCE_STR MATCHES "^\\./" OR SOURCE_STR MATCHES "^\\.\\./" OR SOURCE_STR MATCHES "^/")
    set(IS_LOCAL TRUE)
  endif()

  if(IS_LOCAL)
    get_filename_component(ABS_PATH "${SOURCE_STR}" ABSOLUTE)
    set(RESOLVED "${ABS_PATH}")
  elseif(SOURCE_STR MATCHES "^https?://(www\\.)?github\\.com/([^/]+)/([^/]+)(/(tree|blob)/([^/]+)(/(.*))?)?/?$")
    set(GH_USER "${CMAKE_MATCH_2}")
    set(GH_REPO "${CMAKE_MATCH_3}")
    set(GH_REF  "${CMAKE_MATCH_6}")
    set(GH_FILE "${CMAKE_MATCH_8}")
    
    string(REGEX REPLACE "\\.git$" "" GH_REPO "${GH_REPO}")
    
    if(GH_FILE STREQUAL "")
      set(GH_FILE "recipe.cmake")
    endif()
    
    if(GH_REF STREQUAL "")
      set(RESOLVED "https://raw.githubusercontent.com/${GH_USER}/${GH_REPO}/HEAD/${GH_FILE}")
    else()
      set(RESOLVED "https://raw.githubusercontent.com/${GH_USER}/${GH_REPO}/${GH_REF}/${GH_FILE}")
    endif()
  elseif(SOURCE_STR MATCHES "^https?://")
    set(RESOLVED "${SOURCE_STR}")
  else()
    if(SOURCE_STR MATCHES "^([^/]+)/([^/@#]+)(/([^@#]+))?([@#](.*))?$")
      set(GH_USER "${CMAKE_MATCH_1}")
      set(GH_REPO "${CMAKE_MATCH_2}")
      set(GH_FILE "${CMAKE_MATCH_4}")
      set(GH_REF  "${CMAKE_MATCH_6}")
      
      if(GH_FILE STREQUAL "")
        set(GH_FILE "recipe.cmake")
      endif()
      
      if(GH_REF STREQUAL "")
        set(RESOLVED "https://raw.githubusercontent.com/${GH_USER}/${GH_REPO}/HEAD/${GH_FILE}")
      else()
        set(RESOLVED "https://raw.githubusercontent.com/${GH_USER}/${GH_REPO}/${GH_REF}/${GH_FILE}")
      endif()
    else()
      message(FATAL_ERROR "[Catalog] Invalid recipe source: ${SOURCE_STR}")
    endif()
  endif()
  
  set(${RESULT_VAR} "${RESOLVED}" PARENT_SCOPE)
endfunction()

function(_catalog_resolve_repo_url SOURCE_STR RESULT_VAR TYPE_VAR BASE_VAR NAME_VAR)
  set(IS_LOCAL FALSE)
  if(EXISTS "${SOURCE_STR}" AND IS_DIRECTORY "${SOURCE_STR}")
    set(IS_LOCAL TRUE)
  elseif(SOURCE_STR MATCHES "^\\./" OR SOURCE_STR MATCHES "^\\.\\./" OR SOURCE_STR MATCHES "^/")
    set(IS_LOCAL TRUE)
  endif()
  
  if(IS_LOCAL)
    get_filename_component(ABS_DIR "${SOURCE_STR}" ABSOLUTE)
    set(${RESULT_VAR} "${ABS_DIR}/meta.cmake" PARENT_SCOPE)
    set(${TYPE_VAR} "local" PARENT_SCOPE)
    set(${BASE_VAR} "${ABS_DIR}" PARENT_SCOPE)
    get_filename_component(DIR_NAME "${ABS_DIR}" NAME)
    set(${NAME_VAR} "${DIR_NAME}" PARENT_SCOPE)
  elseif(SOURCE_STR MATCHES "^https?://")
    if(SOURCE_STR MATCHES "\\.cmake$")
      set(RESOLVED "${SOURCE_STR}")
      string(REGEX REPLACE "/[^/]+\\.cmake$" "" BASE "${SOURCE_STR}")
    else()
      string(REGEX REPLACE "/$" "" STR_CLEAN "${SOURCE_STR}")
      set(RESOLVED "${STR_CLEAN}/meta.cmake")
      set(BASE "${STR_CLEAN}")
    endif()
    set(${RESULT_VAR} "${RESOLVED}" PARENT_SCOPE)
    set(${TYPE_VAR} "url" PARENT_SCOPE)
    set(${BASE_VAR} "${BASE}" PARENT_SCOPE)
    string(REGEX MATCH "[^/]+$" URL_NAME "${BASE}")
    set(${NAME_VAR} "${URL_NAME}" PARENT_SCOPE)
  else()
    if(SOURCE_STR MATCHES "^([^/]+)/([^@#]+)([@#](.+))?$")
      set(GH_USER "${CMAKE_MATCH_1}")
      set(GH_REPO "${CMAKE_MATCH_2}")
      set(GH_REF "${CMAKE_MATCH_4}")
      if(GH_REF STREQUAL "")
        set(GH_REF "HEAD")
      endif()
      
      set(RESOLVED "https://raw.githubusercontent.com/${GH_USER}/${GH_REPO}/${GH_REF}/meta.cmake")
      set(BASE "https://raw.githubusercontent.com/${GH_USER}/${GH_REPO}/${GH_REF}")
      
      set(${RESULT_VAR} "${RESOLVED}" PARENT_SCOPE)
      set(${TYPE_VAR} "github" PARENT_SCOPE)
      set(${BASE_VAR} "${BASE}" PARENT_SCOPE)
      set(${NAME_VAR} "${GH_USER}_${GH_REPO}" PARENT_SCOPE)
    else()
      _catalog_log(FATAL_ERROR "Invalid repository source: ${SOURCE_STR}")
    endif()
  endif()
endfunction()

function(_catalog_find_pkgconfig_package PACKAGE_NAME RESULT_VAR)
  find_package(PkgConfig QUIET)
  if(PkgConfig_FOUND)
    pkg_check_modules(PKG_CONFIG_${PACKAGE_NAME} QUIET ${PACKAGE_NAME})
    if(PKG_CONFIG_${PACKAGE_NAME}_FOUND)
      set(${RESULT_VAR} TRUE PARENT_SCOPE)
    else()
      set(${RESULT_VAR} FALSE PARENT_SCOPE)
    endif()
  else()
    set(${RESULT_VAR} FALSE PARENT_SCOPE)
  endif()
endfunction()

function(_catalog_get_cache_dir RESULT_VAR)
  _catalog_get_var("CACHE_DIR" CACHE_DIR_VAL ENV)
  _catalog_is_var_defined("LOCAL_CACHE" HAS_LOCAL_CACHE ENV)

  if(NOT "${CACHE_DIR_VAL}" STREQUAL "")
    set(CACHE_DIR "${CACHE_DIR_VAL}")
  elseif(CMAKE_CROSSCOMPILING OR HAS_LOCAL_CACHE)
    set(CACHE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/.cache/catalog")
  else()
    if(WIN32)
      set(CACHE_DIR "$ENV{LOCALAPPDATA}/catalog")
    else()
      set(CACHE_DIR "$ENV{HOME}/.cache/catalog")
    endif()
  endif()
  
  file(MAKE_DIRECTORY "${CACHE_DIR}")
  set(${RESULT_VAR} "${CACHE_DIR}" PARENT_SCOPE)
endfunction()

function(_catalog_load_recipe RECIPE_URL RECIPE_OUTPUT_VAR)
  if(NOT RECIPE_URL)
    _catalog_log(FATAL_ERROR "Recipe URL cannot be empty")
  endif()
  
  if(EXISTS "${RECIPE_URL}")
    set(${RECIPE_OUTPUT_VAR} "${RECIPE_URL}" PARENT_SCOPE)
    return()
  endif()
  
  _catalog_get_cache_dir(CACHE_DIR)
  
  string(SHA256 RECIPE_HASH "${RECIPE_URL}")
  string(SUBSTRING "${RECIPE_HASH}" 0 12 RECIPE_HASH_SHORT)
  set(RECIPE_FILE "${CACHE_DIR}/recipe_${RECIPE_HASH_SHORT}.cmake")
  
  if(NOT EXISTS ${RECIPE_FILE})
    _catalog_download_file(${RECIPE_URL} ${RECIPE_FILE})
  endif()
  
  set(${RECIPE_OUTPUT_VAR} "${RECIPE_FILE}" PARENT_SCOPE)
endfunction()

function(_catalog_valid_target_name NAME RESULT_VAR)
  if(NAME MATCHES "^[a-zA-Z0-9_:-]+$")
    set(${RESULT_VAR} TRUE PARENT_SCOPE)
  else()
    set(${RESULT_VAR} FALSE PARENT_SCOPE)
  endif()
endfunction()
